package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"time"

	homedir "github.com/mitchellh/go-homedir"
	"github.com/urfave/cli"
)

var (
	host      string
	tls       bool
	tlscacert string
	tlscert   string
	tlskey    string
	tlsverify bool
	output    string
	help      bool
)

func main() {
	home, err := homedir.Dir()
	capath := ""
	certpath := ""
	keypath := ""
	if err == nil {
		capath = filepath.Join(home, ".docker", "ca.pem")
		certpath = filepath.Join(home, ".docker", "cert.pem")
		keypath = filepath.Join(home, ".docker", "key.pem")
	}

	app := cli.NewApp()
	app.HideHelp = true
	app.Name = "dctc"
	app.Usage = "generate a docker-compose.yml from a container"
	app.Version = "0.1.0"
	app.ArgsUsage = "NAME|ID [NAME|ID...]"
	app.Copyright = "Copyright (c) 2019 tenfy"
	app.Compiled = time.Now()
	app.Authors = []cli.Author{
		cli.Author{Name: "tenfy", Email: "tenfy@tenfy.cn"},
	}
	app.Flags = []cli.Flag{
		cli.StringFlag{
			Name:        "host, H",
			Value:       "unix:///var/run/docker.sock",
			Usage:       "Daemon `socket` to connect to",
			Destination: &host,
		},
		cli.StringFlag{
			Name:        "output, o",
			Usage:       "Write output to `file`, default: stdout",
			Destination: &output,
		},
		cli.BoolFlag{
			Name:        "tls",
			Usage:       "Use TLS; implied by --tlsverify",
			Destination: &tls,
		},
		cli.StringFlag{
			Name:        "tlscacert",
			Usage:       "Trust certs signed only by this CA",
			Value:       capath,
			Destination: &tlscacert,
		},
		cli.StringFlag{
			Name:        "tlscert",
			Usage:       "Path to TLS certificate file",
			Value:       certpath,
			Destination: &tlscert,
		},
		cli.StringFlag{
			Name:        "tlskey",
			Usage:       "Path to TLS key file",
			Value:       keypath,
			Destination: &tlskey,
		},
		cli.BoolFlag{
			Name:        "tlsverify",
			Usage:       "Use TLS and verify the remote",
			Destination: &tlsverify,
		},
		cli.BoolFlag{
			Name:        "help, h",
			Usage:       "Show help",
			Destination: &help,
		},
	}

	app.Action = func(c *cli.Context) error {
		if help {
			cli.ShowAppHelpAndExit(c, 0)
		}

		if c.NArg() == 0 {
			fmt.Fprintf(os.Stderr, "dctc requires at least 1 argument(s)\n\n")
			cli.ShowAppHelpAndExit(c, -1)
		}

		client, err := newClient()
		if err != nil {
			return err
		}

		str, err := dctc(client, []string(c.Args()))
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			return err
		}

		str = fmt.Sprintf("### generated by dctc (https://github.com/tenfyzhong/dctc)\n### host: %s\n\n%s", host, str)

		if output == "" {
			fmt.Println(str)
		} else {
			err := ioutil.WriteFile(output, []byte(str), 0644)
			if err != nil {
				fmt.Fprintln(os.Stderr, err)
				return err
			}
		}

		return nil
	}

	app.Run(os.Args)
}
